baseURL = "/"
languageCode = "en-us"
title = ""
theme = "base"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  description = "Free Chicago tours from this no-app local guide. Get a text or audio tour on your phone without installing anything."
  title = "Chicago Local Tours"
  headerImage  = "images/header.png"
  author = "Website Tours of Chicago"
  imageSizes = "1280 768 640 320"
  imageFormats = "webp jpeg"